- name: this is my first ansible with jenkins
  hosts: dev
  tasks: 
    - name: file module
      file:
          path: /tmp/ganeshjoshi.txt
          state: touch
          mode: u+rw,g-wx,o-rwx

    - name: copy module
      copy: 
        content:  "I will do"
        dest: /tmp/ganeshjoshi.txt
